os:
  - linux

dist: trusty
sudo: false
language: node_js

cache:
  yarn: true
  npm: true

jobs:
  include:
    - &testyarn
      stage: test
      name: Test on Node 8
      node_js: '8'
      install:
        - yarn
      script:
        - yarn test
    - <<: *testyarn
      name: Test on Node 10
      node_js: '10'

    - &testnpm
      stage: test
      name: Test on Node 8
      node_js: '8'
      install:
        - npm ci
      script:
        - npm test
    - <<: *testnpm
      name: Test on Node 10
      node_js: '10'

    - &buildyarn
      stage: build
      name: Build on Node 8
      node_js: '8'
      install:
        - yarn
      script:
        - yarn build
    - <<: *buildyarn
      name: Build on Node 10
      node_js: '10'

    - &buildnpm
      stage: build
      name: Build on Node 8
      node_js: '8'
      install:
        - npm ci
      script:
        - npm build
    - <<: *buildnpm
      name: Build on Node 10
      node_js: '10'
