[build]
command = "npm run build"
publish = "public"

[[redirects]]
from = "/discord"
status = 302
to = "https://discord.gg/sPazfrt"

[[redirects]]
from = "/github"
status = 302
to = "https://github.com/jbolda/finatr"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"
