name: covector status
on: [pull_request]

jobs:
  covector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: volta-cli/action@v4
      - name: covector status
        uses: jbolda/covector/packages/action@main
        id: covector
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: 'status'
          comment: true
