name: e2e on push

on: pull_request

jobs:
  chrome:
    runs-on: ubuntu-16.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v1
        with:
          browser: chrome
          record: true
          group: chrome
          start: npm start
          wait-on: 'http://localhost:3000'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  firefox:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001
    steps:
      - uses: actions/checkout@v2
      - run: echo "skipping this for now due to errors"
      - run: echo "see this issue https://github.com/jbolda/finatr/pull/313/checks?check_run_id=650933290"
      # - uses: cypress-io/github-action@v1
      #   with:
      #     browser: firefox
      #     record: true
      #     group: firefox
      #     build: yarn cy:info # to output the detected browsers
      #     start: yarn start
      #     wait-on: 'http://localhost:3000'
      #   env:
      #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  edge:
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - run: echo "skipping this for now due to errors"
      - run: echo "see this issue https://github.com/jbolda/finatr/pull/313/checks?check_run_id=650933262"
      # - uses: cypress-io/github-action@v1
      #   with:
      #     browser: edge
      #     record: true
      #     group: edge
      #     build: yarn cy:info # to output the detected browsers
      #     start: yarn start
      #     wait-on: 'http://localhost:3000'
      #     config-file: ./cypress.json
      #   env:
      #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     ACTIONS_RUNNER_DEBUG: true
      #     ACTIONS_STEP_DEBUG: true
