name: unit tests
on:
  pull_request:
  push:
    branches: [next]

jobs:
  test:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: npm ci
      - run: npm test
      - run: npm run build
