name: unit tests
on:
  pull_request:
  push:
    branches: [next]

jobs:
  test:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: npm ci
      - name: Install Playwright Browsers
        run: npm run playwright install --with-deps -c playwright-ct.config.ts
      - run: npm run test-ct
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
