name: e2e on push

on: [push]
jobs:
  chrome:
    runs-on: ubuntu-16.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v1
        with:
          browser: chrome
          record: true
          start: yarn start
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  firefox:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 30
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v1
        with:
          browser: firefox
          record: true
          start: yarn start
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  edge:
    runs-on: windows-latest
    continue-on-error: true
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v1
        with:
          browser: edge
          record: true
          start: yarn start
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
