name: e2e

on:
  pull_request:
  push:
    branches: [next]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npm run playwright install --with-deps
      - name: Run Playwright tests
        run: npm run playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
